from pyparsing import line
from utils import calc 
import numpy as np
import os
def create_plot_xml(path_to_states,output_path,t0,name_xml="prin_corr.xml"):
    directories = os.listdir(path_to_states)
    with open(f"{output_path}/{name_xml}","w") as f:
        f.write("<prin_corrs>\n")
        for folder in directories:
            if "unord" in folder:
                continue
            num = folder.split("ord")[1]
            name = f"prin_corrs_t0_{t0}_reorder_state{num}.ax"
            plot_path = f"{path_to_states}/{folder}/plot.ax"
            
            if not os.path.exists(plot_path):
                print(f"File {plot_path} does not exist, skipping plotting...")
                continue
            f.write(f"   <plot {name}>\n")
            with open(plot_path, 'r') as plot_file:
                lines = plot_file.readlines()
                for line in lines:
                    f.write(line)
            f.write(f"   </plot {name}>\n")
        f.write("</prin_corrs>\n")
def calculate_ZFactor_and_error_twopt(path_to_states,output_path,t0,name_xml="ZFactor.xml"):
    """
    Function used to store the Z factors and errors of the states generated by twopt.
    :param path_to_states: The path to the directory containing the states @ord{num} in out/z
    :param output_path: The path to the output directory where xml will be stored
    :param name_xml: The name of the output xml file (default is ZFactor.xml)
    """
    directories = os.listdir(path_to_states)
    with open(f"{output_path}/{name_xml}","w") as f:
        f.write("<ZFactors>\n")

        for folder in directories:
            if "unord" in folder:
                continue
            operator_folders = os.listdir(f"{path_to_states}/{folder}")
            for op_folder in operator_folders:
                if "op" not in op_folder:
                    continue
                
                path_zfactor = f"{path_to_states}/{folder}/{op_folder}/C.jack"
                model_averaging = False
                model_avg_path = f"{path_to_states}/{folder}/{op_folder}/C.vars"

                if not os.path.exists(path_zfactor):
                    print(f"Overlap of {op_folder} to {folder} does not exist, skipping...")
                    continue
                if os.path.exists(model_avg_path):
                    with open(model_avg_path,"r") as fit_file:
                        lines = fit_file.readlines()
                        for i,line in enumerate(lines):
                            split = line.split("  ")
                            if split[0] == "-1":
                                model_avg_value = float(split[1].split()[0])
                                model_avg_err = float(split[1].split()[1])
                                model_averaging = True
                            if i ==len(lines)-1 and not model_averaging:
                                print(f"Model average not found for {folder}/{op_folder}, skipping...")
                    
                avg, err = calc(path_zfactor)
                avg = abs(float(avg))
                num_state = folder.split("ord")[1]
                num_op = op_folder.split("op")[1]
                name = f"Z_t0_{t0}_reorder_state{num_state}_op{num_op}.jack"

                f.write("   <elem>\n")
                f.write(f"      <name>{name}</name>\n")
                f.write(f"      <value>{avg}</value>\n")
                f.write(f"      <error>{err}</error>\n")
                if model_averaging:
                    f.write(f"      <model_average_value>{abs(model_avg_value)}</model_average_value>\n")
                    f.write(f"      <model_average_error>{model_avg_err}</model_average_error>\n")
                f.write(f"   </elem>\n")
        f.write("</ZFactors>\n")


def calculate_masses_and_error_reconfit(path_to_states,output_path,t0,name_xml="energies.xml"):
    """
    Function used to store the energies and errors of the states generated by twopt.
    :param path_to_states: The path to the directory containing the states @ord{num} in out/prin_corrs
    :param output_path: The path to the output directory where xml will be stored
    :param t0: The value of t0 of the energy set to be stored
    :param name_xml: The name of the output xml file (default is energies.xml)
    """

    i  = 0
    path_energies = f"{path_to_states}/MassJackFiles"
    directories = os.listdir(path_energies)
    path_vars = f"{path_to_states}/PrinCorrFitLogs"
    with open(f"{output_path}/{name_xml}","w") as f:
        f.write("<energies>\n")

        for file in directories:
            if not file.endswith(".jack"):
                continue
            path_energy = f"{path_energies}/{file}"

            if not os.path.exists(path_energy):
                print(f"File {path_energy} does not exist, skipping...")
                continue
            state_num = file.split("state")[1].split(".")[0]
            t0 = file.split("t0_")[1].split("_")[0]
            princcorrs = f"prin_corr_fit_log_t0{t0}_reorder_state{state_num}.log"
            path_fits = f"{path_vars}/{princcorrs}"
            with open(path_fits,"r") as fit_file:
                lines = fit_file.readlines()
                fit_options = {}
                for i,line in enumerate(lines):
                    if i == 0:
                        continue
                    if i == 1:
                        continue
                    
                    split = line.split("|")
                    name = split[0].strip()
                    chisq = split[1].strip()
                    Q = split[2].strip()
                    P = split[3].strip()
                    m = split[4].split(",")[0].strip()
                    print(m)
                    value = m.split("m= ")[1].strip()
                    error = m.split("+/-")[1].strip()
                    fit_options[name] = {
                        "value": float(value),
                        "error": float(error),
                        "chi_square": chisq,
                        "P": P
                    }

                
                    
            
            

            
            avg,err = calc(path_energy)
            f.write("   <elem>\n")
            f.write(f"      <name>{file}</name>\n")
            f.write(f"      <value>{avg}</value>\n")
            f.write(f"      <error>{err}</error>\n")

            
            f.write(f"      <fit options>\n")
            for name in fit_options.keys():
                f.write(f"       <option>\n")
                f.write(f"           <name>{name}</name>\n")
                f.write(f"           <value>{fit_options[name]['value']}</value>\n")
                f.write(f"           <error>{fit_options[name]['error']}</error>\n")
                f.write(f"           <chi_square>{fit_options[name]['chi_square']}</chi_square>\n")
                f.write(f"           <P>{fit_options[name]['P']}</P>\n")
                f.write(f"      </option>\n")
            f.write(f"      </fit options>\n")
            f.write(f"   </elem>\n")
        f.write("</energies>\n")

