from pyparsing import line
from utils import calc 
import numpy as np
import os

def create_pc_xml(path_to_states,output_path,t0,name_xml="pc.xml"):
    directories = os.listdir(path_to_states)
    with open(f"{output_path}/{name_xml}","w") as f:
        f.write("<prin_corrs data>\n")
        for folder in directories:
            if "unord" in folder:
                continue
            num = folder.split("ord")[1]
            name = f"prin_corrs_t0_{t0}_reorder_state{num}.jack"
            plot_path = f"{path_to_states}/{folder}/pc.jack"
            
            if not os.path.exists(plot_path):
                print(f"File {plot_path} does not exist, skipping pc collection...")
                continue
            f.write(f"   <pc {name}>\n")
            with open(plot_path, 'r') as plot_file:
                lines = plot_file.readlines()
                for line in lines:
                    f.write(line)
            f.write(f"   </pc {name}>\n")
        f.write("</prin_corrs data>\n")
def create_plot_xml(path_to_states,output_path,t0,name_xml="prin_corr.xml"):
    directories = os.listdir(path_to_states)
    with open(f"{output_path}/{name_xml}","w") as f:
        f.write("<prin_corrs>\n")
        for folder in directories:
            if "unord" in folder:
                continue
            num = folder.split("ord")[1]
            name = f"prin_corrs_t0_{t0}_reorder_state{num}.ax"
            plot_path = f"{path_to_states}/{folder}/plot.ax"
            
            if not os.path.exists(plot_path):
                print(f"File {plot_path} does not exist, skipping plotting...")
                continue
            f.write(f"   <plot {name}>\n")
            with open(plot_path, 'r') as plot_file:
                lines = plot_file.readlines()
                for line in lines:
                    f.write(line)
            f.write(f"   </plot {name}>\n")
        f.write("</prin_corrs>\n")
def calculate_ZFactor_and_error_twopt(path_to_states,output_path,t0,name_xml="ZFactor.xml"):
    """
    Function used to store the Z factors and errors of the states generated by twopt.
    :param path_to_states: The path to the directory containing the states @ord{num} in out/z
    :param output_path: The path to the output directory where xml will be stored
    :param name_xml: The name of the output xml file (default is ZFactor.xml)
    """
    directories = os.listdir(path_to_states)
    with open(f"{output_path}/{name_xml}","w") as f:
        f.write("<ZFactors>\n")

        for folder in directories:
            if "unord" in folder:
                continue
            operator_folders = os.listdir(f"{path_to_states}/{folder}")
            for op_folder in operator_folders:
                if "op" not in op_folder:
                    continue
                
                path_zfactor = f"{path_to_states}/{folder}/{op_folder}/Z.jack"
                model_averaging = False
                model_avg_path = f"{path_to_states}/{folder}/{op_folder}/C.vars"

                if not os.path.exists(path_zfactor):
                    print(f"Overlap of {op_folder} to {folder} does not exist, skipping...")
                    continue
                if os.path.exists(model_avg_path):
                    with open(model_avg_path,"r") as fit_file:
                        lines = fit_file.readlines()
                        for i,line in enumerate(lines):
                            split = line.split("  ")
                            if split[0] == "-1":
                                model_avg_value = float(split[1].split()[0])
                                model_avg_err = float(split[1].split()[1])
                                model_averaging = True
                            if i ==len(lines)-1 and not model_averaging:
                                print(f"Model average not found for {folder}/{op_folder}, skipping...")
                    
                avg, err = calc(path_zfactor)
                avg = abs(float(avg))
                num_state = folder.split("ord")[1]
                num_op = op_folder.split("op")[1]
                name = f"Z_t0_{t0}_reorder_state{num_state}_op{num_op}.jack"

                f.write("   <elem>\n")
                f.write(f"      <name>{name}</name>\n")
                f.write(f"      <value>{avg}</value>\n")
                f.write(f"      <error>{err}</error>\n")
                if model_averaging:
                    f.write(f"      <model_average_value_z>{abs(model_avg_value)}</model_average_value_z>\n")
                    f.write(f"      <model_average_error_z>{model_avg_err}</model_average_error_z>\n")
                f.write(f"   </elem>\n")
        f.write("</ZFactors>\n")


def calculate_masses_and_error_twopt(path_to_states,output_path,t0,name_xml="energies.xml"):
    """
    Function used to store the energies and errors of the states generated by twopt.
    :param path_to_states: The path to the directory containing the states @ord{num} in out/prin_corrs
    :param output_path: The path to the output directory where xml will be stored
    :param t0: The value of t0 of the energy set to be stored
    :param name_xml: The name of the output xml file (default is energies.xml)
    """

    i  = 0
    directories = os.listdir(path_to_states)
    with open(f"{output_path}/{name_xml}","w") as f:
        f.write("<energies>\n")

        for folder in directories:
            if "unord" in folder:
                continue
            path_energy = f"{path_to_states}/{folder}/m.jack"

            if not os.path.exists(path_energy):
                print(f"File {path_energy} does not exist, skipping...")
                continue
            path_fits = f"{path_to_states}/{folder}/m.vars"
            path_A = f"{path_to_states}/{folder}/A.vars"
            path_dm = f"{path_to_states}/{folder}/dm.vars"
            if os.path.exists(path_A):
                A_variation = True
            else:
                A_variation = False
                path_A = path_fits
            if os.path.exists(path_dm):
                dm_variation = True

            else:
                dm_variation = False
                path_dm = path_fits

            model_averaging = False
            with open(path_fits,"r") as fit_file:
                with open(path_A,"r") as A_file:
                        with open(path_dm,"r") as dm_file:

                            lines = fit_file.readlines()
                            lines_A = A_file.readlines()
                            lines_dm = dm_file.readlines()
                            fit_options = {}
                            j = 0
                            for i,line in enumerate(lines):
                                split = line.split("  ")
                                split_A = lines_A[j].split("  ")
                                split_dm = lines_dm[j].split("  ")
                                if split[0] == "-1":
                                    model_avg_value = float(split[1].split()[0])
                                    model_avg_err = float(split[1].split()[1])
                                    model_averaging = True
                                    if dm_variation:
                                        model_avg_value_dm = float(split_dm[1].split()[0])
                                        model_avg_err_dm = float(split_dm[1].split()[1])
                                    if A_variation:
                                        model_avg_value_A = float(split_A[1].split()[0])
                                        model_avg_err_A = float(split_A[1].split()[1])
                                    if A_variation and dm_variation:
                                        fit_options["model_average"] = (model_avg_value, model_avg_err,model_avg_value_A,model_avg_err_A,model_avg_value_dm,model_avg_err_dm)
                                    else:
                                        fit_options["model_average"] = (model_avg_value, model_avg_err)

                                elif split[0].isnumeric() and split[0] != "0":

                                    value = float(split[1].split()[0])
                                    error = float(split[1].split()[1])

                                    name = line.split("|")[1].strip()
                                    if "1exp" not in name and A_variation and dm_variation:
                                        
                                        value_dm = float(split_dm[1].split()[0])
                                        err_dm = float(split_dm[1].split()[1])
                                        value_A = float(split_A[1].split()[0])
                                        err_A = float(split_A[1].split()[1])
                                        try:

                                            P_A = lines_A[j].split("|")[3].strip()
                                            P_dm = lines_dm[j].split("|")[3].strip()
                                        except:
                                            P_A = ""
                                            P_dm = ""
                                    else:
                                        value_dm = "-"
                                        err_dm = "-"
                                        value_A = "-"
                                        err_A = "-"
                                        P_dm = "-"
                                        P_A = "-"
                                    if "1exp" in name and A_variation and dm_variation:
                                        j-=1
                                    chi_square = line.split("|")[2].strip()
                                    try:
                                        P = line.split("|")[3].strip()
                                    except:
                                        P = "-"
                                    fit_options[name] = {
                                        "value": value,
                                        "error": error,
                                        "chi_square": chi_square,
                                        "P": P,
                                        "dm":value_dm,
                                        "err_dm":err_dm,
                                        "P_dm":P_dm,
                                        "A":value_A,
                                        "err_A":err_A,
                                        "P_A":P_A

                                    }
                                elif split[0] == "0":
                                    value = float(split[1].split()[0])
                                    error = float(split[1].split()[1])
                                    name = line.split("|")[1].strip()
                                    print(split_dm)
                                    if "1exp" not in name and A_variation and dm_variation:
                                        
                                        value_dm = float(split_dm[1].split()[0])
                                        err_dm = float(split_dm[1].split()[1])
                                        value_A = float(split_A[1].split()[0])
                                        err_A = float(split_A[1].split()[1])
                                        P_dm = "N/A"
                                        P_A = "N/A"
                                    else:
                                        value_dm = "-"
                                        err_dm = "-"
                                        value_A = "-"
                                        err_A = "-"
                                        P_dm = "-"
                                        P_A = "-"
                                    if "1exp" in name and A_variation and dm_variation:
                                        j-=1
 
                                    name = "Chosen fit"
                                    chi_square = line.split("|")[2].strip()
                                    fit_options[name] = {
                                        "value": value,
                                        "error": error,
                                        "chi_square": chi_square,
                                        "P": "N/A",
                                        "dm":value_dm,
                                        "err_dm":err_dm,
                                        "P_dm":P_dm,
                                        "A":value_A,
                                        "err_A":err_A,
                                        "P_A":P_A

                                    }



                                
                                if i ==len(lines)-1:
                                    print(f"Model average not found for {folder}, skipping...")
                                j += 1
                    
                    
                    
                    
            
            num = ""
            for ch in folder:
                if ch.isnumeric():
                    num += ch

            name = f"mass_t0_{t0}_reorder_state{num}.jack"
            avg,err = calc(path_energy)
            f.write("   <elem>\n")
            f.write(f"      <name>{name}</name>\n")
            f.write(f"      <value>{avg}</value>\n")
            f.write(f"      <error>{err}</error>\n")
            if model_averaging:
                f.write(f"      <model_average_value>{model_avg_value}</model_average_value>\n")
                f.write(f"      <model_average_error>{model_avg_err}</model_average_error>\n")
                if len(fit_options["model_average"])>2:
                    model_averaging,model_avg_err,model_avg_value_A,model_avg_err_A,model_avg_value_dm,model_avg_err_dm = fit_options["model_average"]                
                    f.write(f"      <model_average_value_A>{model_avg_value_A}</model_average_value_A>\n")
                    f.write(f"      <model_average_error_A>{model_avg_err_A}</model_average_error_A>\n")
                    f.write(f"      <model_average_value_dm>{model_avg_value_dm}</model_average_value_dm>\n")
                    f.write(f"      <model_average_error_dm>{model_avg_err_dm}</model_average_error_dm>\n")


            if True:
                f.write(f"      <fit options>\n")
                for name in fit_options.keys():
                    if name == "model_average":
                        continue

                    f.write(f"       <option>\n")
                    f.write(f"           <name>{name}</name>\n")
                    f.write(f"           <value>{fit_options[name]['value']}</value>\n")
                    f.write(f"           <error>{fit_options[name]['error']}</error>\n")
                    f.write(f"           <chi_square>{fit_options[name]['chi_square']}</chi_square>\n")
                    f.write(f"           <P>{fit_options[name]['P']}</P>\n")
                    f.write(f"           <A>{fit_options[name]['A']}</A>\n")
                    f.write(f"           <A_err>{fit_options[name]['err_A']}</A_err>\n")
                    f.write(f"           <P_A>{fit_options[name]['P_A']}</P_A>\n")
                    f.write(f"           <dm>{fit_options[name]['dm']}</dm>\n")
                    f.write(f"           <dm_err>{fit_options[name]['err_dm']}</dm_err>\n")
                    f.write(f"           <P_dm>{fit_options[name]['P_dm']}</P_dm>\n")



                    f.write(f"      </option>\n")
                f.write(f"      </fit options>\n")
            f.write(f"   </elem>\n")
        f.write("</energies>\n")

