from pyparsing import line
from utils import calc 
import numpy as np
import os
def calculate_ZFactor_and_error_twopt(path_to_states,output_path,t0,name_xml="ZFactor.xml"):
    """
    Function used to store the Z factors and errors of the states generated by twopt.
    :param path_to_states: The path to the directory containing the states @ord{num} in out/z
    :param output_path: The path to the output directory where xml will be stored
    :param name_xml: The name of the output xml file (default is ZFactor.xml)
    """
    directories = os.listdir(path_to_states)
    with open(f"{output_path}/{name_xml}","w") as f:
        f.write("<ZFactors>\n")

        for folder in directories:
            if "unord" in folder:
                continue
            operator_folders = os.listdir(f"{path_to_states}/{folder}")
            for op_folder in operator_folders:
                if "op" not in op_folder:
                    continue
                
                path_zfactor = f"{path_to_states}/{folder}/{op_folder}/C.jack"
                model_averaging = False
                model_avg_path = f"{path_to_states}/{folder}/{op_folder}/C.vars"

                if not os.path.exists(path_zfactor):
                    print(f"Overlap of {op_folder} to {folder} does not exist, skipping...")
                    continue
                if os.path.exists(model_avg_path):
                    with open(model_avg_path,"r") as fit_file:
                        lines = fit_file.readlines()
                        for i,line in enumerate(lines):
                            split = line.split("  ")
                            if split[0] == "-1":
                                model_avg_value = float(split[1].split()[0])
                                model_avg_err = float(split[1].split()[1])
                                model_averaging = True
                            if i ==len(lines)-1 and not model_averaging:
                                print(f"Model average not found for {folder}/{op_folder}, skipping...")
                    
                avg, err = calc(path_zfactor)
                avg = abs(float(avg))
                num_state = folder.split("ord")[1]
                num_op = op_folder.split("op")[1]
                name = f"Z_t0_{t0}_reorder_state{num_state}_op{num_op}.jack"

                f.write("   <elem>\n")
                f.write(f"      <name>{name}</name>\n")
                f.write(f"      <value>{avg}</value>\n")
                f.write(f"      <error>{err}</error>\n")
                if model_averaging:
                    f.write(f"      <model_average_value>{abs(model_avg_value)}</model_average_value>\n")
                    f.write(f"      <model_average_error>{model_avg_err}</model_average_error>\n")
                f.write(f"   </elem>\n")
        f.write("</ZFactors>\n")


def calculate_masses_and_error_twopt(path_to_states,output_path,t0,name_xml="energies.xml"):
    """
    Function used to store the energies and errors of the states generated by twopt.
    :param path_to_states: The path to the directory containing the states @ord{num} in out/prin_corrs
    :param output_path: The path to the output directory where xml will be stored
    :param t0: The value of t0 of the energy set to be stored
    :param name_xml: The name of the output xml file (default is energies.xml)
    """

    i  = 0
    directories = os.listdir(path_to_states)
    with open(f"{output_path}/{name_xml}","w") as f:
        f.write("<energies>\n")

        for folder in directories:
            if "unord" in folder:
                continue
            path_energy = f"{path_to_states}/{folder}/m.jack"

            if not os.path.exists(path_energy):
                print(f"File {path_energy} does not exist, skipping...")
                continue
            path_fits = f"{path_to_states}/{folder}/m.vars"
            model_averaging = False
            with open(path_fits,"r") as fit_file:
                lines = fit_file.readlines()
                fit_options = {}
                for i,line in enumerate(lines):
                    
                    split = line.split("  ")
                    if split[0] == "-1":
                        model_avg_value = float(split[1].split()[0])
                        model_avg_err = float(split[1].split()[1])
                        model_averaging = True
                        fit_options["model_average"] = (model_avg_value, model_avg_err)
                    elif split[0].isnumeric() and split[0] != "0":

                        value = float(split[1].split()[0])
                        error = float(split[1].split()[1])
                        name = line.split("|")[1].strip()
                        chi_square = line.split("|")[2].strip()
                        P = line.split("|")[3].strip()
                        fit_options[name] = {
                            "value": value,
                            "error": error,
                            "chi_square": chi_square,
                            "P": P
                        }
                    elif split[0] == "0":
                        value = float(split[1].split()[0])
                        error = float(split[1].split()[1])
                        name = "Chosen fit"
                        chi_square = line.split("|")[2].strip()
                        fit_options[name] = {
                            "value": value,
                            "error": error,
                            "chi_square": chi_square,
                            "P": "N/A"
                        }



                    
                    if i ==len(lines)-1:
                        print(f"Model average not found for {folder}, skipping...")
                
                
                
                    
            
            num = ""
            for ch in folder:
                if ch.isnumeric():
                    num += ch

            name = f"mass_t0_{t0}_reorder_state{num}.jack"
            avg,err = calc(path_energy)
            f.write("   <elem>\n")
            f.write(f"      <name>{name}</name>\n")
            f.write(f"      <value>{avg}</value>\n")
            f.write(f"      <error>{err}</error>\n")
            if model_averaging:
                f.write(f"      <model_average_value>{model_avg_value}</model_average_value>\n")
                f.write(f"      <model_average_error>{model_avg_err}</model_average_error>\n")
            if model_averaging:
                f.write(f"      <fit options>\n")
                for name in fit_options.keys():
                    if name == "model_average":
                        continue

                    f.write(f"       <option>\n")
                    f.write(f"           <name>{name}</name>\n")
                    f.write(f"           <value>{fit_options[name]['value']}</value>\n")
                    f.write(f"           <error>{fit_options[name]['error']}</error>\n")
                    f.write(f"           <chi_square>{fit_options[name]['chi_square']}</chi_square>\n")
                    f.write(f"           <P>{fit_options[name]['P']}</P>\n")
                    f.write(f"      </option>\n")
                f.write(f"      </fit options>\n")
            f.write(f"   </elem>\n")
        f.write("</energies>\n")

